// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzIIoC3C-M7C66sqT9dYqi7K4jeXdNU6Q',
    appId: '1:213748404792:web:bc7d737e9710205ea30ccd',
    messagingSenderId: '213748404792',
    projectId: 'veil-app-anonymous',
    authDomain: 'veil-app-anonymous.firebaseapp.com',
    storageBucket: 'veil-app-anonymous.firebasestorage.app',
    measurementId: 'G-TJB7VPN0H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrzdjnWTDXy0g-QMa08uAqpv_GHgaslDk',
    appId: '1:213748404792:android:d53d841bb34c03eba30ccd',
    messagingSenderId: '213748404792',
    projectId: 'veil-app-anonymous',
    storageBucket: 'veil-app-anonymous.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvCPEIRbdpWIZ2PCECnLqY8Ggp9lZxD_M',
    appId: '1:213748404792:ios:6def9305217dde19a30ccd',
    messagingSenderId: '213748404792',
    projectId: 'veil-app-anonymous',
    storageBucket: 'veil-app-anonymous.firebasestorage.app',
    iosClientId: '213748404792-frc97evo89g9a0fiq6aq1bj8d4sph3a6.apps.googleusercontent.com',
    iosBundleId: 'com.bakchodi.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzIIoC3C-M7C66sqT9dYqi7K4jeXdNU6Q',
    appId: '1:213748404792:web:228bd505427af283a30ccd',
    messagingSenderId: '213748404792',
    projectId: 'veil-app-anonymous',
    authDomain: 'veil-app-anonymous.firebaseapp.com',
    storageBucket: 'veil-app-anonymous.firebasestorage.app',
    measurementId: 'G-PHCW00T7PS',
  );

}